timesteps: [0,125]

blur_kernel_size: 11
system_g: 3

name: "${dataset}_${exp_setting}_decode_${brain_backbone}_${vision_backbone}"

models:
  brain:
    target: "base.eeg_backbone.${brain_backbone}"
    params:
        c_num: 17
        z_dim: ${z_dim}
        timesteps: ${timesteps}

data:
  data_dir: data/things-eeg/Preprocessed_data_250Hz_whiten
  #selected_ch: None
  selected_ch: ['P7', 'P5', 'P3', 'P1','Pz', 'P2', 'P4', 'P6', 'P8', 'PO7', 'PO3', 'POz', 'PO4', 'PO8','O1', 'Oz', 'O2']
  model_type: ${vision_backbone}
  train_batch_size: 4096
  val_batch_size: 200
  test_batch_size: 200
  uncertainty_aware: False
  blur_type:
    target: base.inpating_data.PerfectCenterFoveaBlur
    params:
          h: 224
          w: 224
          blur_kernel_size: 17
          clear_radius: 16
          decay_rate: 8.0

  train_avg: True
  test_avg: True
  timesteps: ${timesteps}

train:
  epoch: ${epoch}
  optimizer: AdamW
  lr: ${lr}
  
save_dir: 'exp_img_fanhhua_new'